import { WASMCode, WASMModule, WASMCodeParameter } from "../wasm-vm/wasm-code"
import {
  ASTFunction,
  ASTFunctionInstruction,
  AnyParameter
} from "../wat-parser/func"
import { ASTModule } from "../wat-parser/module"
import { flatten } from "../misc/array"
import { ASTBlock, isBlockInstruction } from "../wat-parser/block"
import { NumberValue, ValType } from "../wat-parser/types"
import { Int32 } from "../number/Int32"
import { replaceIdentifiers } from "./precompile"

const compileInstruction = (
  inst: ASTFunctionInstruction<AnyParameter>
): WASMCode[] => {
  if (isBlockInstruction(inst)) {
    const block = inst as ASTBlock
    return compileBlock(block)
  }

  return [inst]
}

const compileBlock = (block: ASTBlock): WASMCode[] => {
  return [block]
}

export const numberValue = (type: ValType, value: string): NumberValue => {
  switch (type) {
    case ValType.i32:
      return { [type]: value }
    case ValType.i64:
      return { [type]: value }
    case ValType.f32:
      return { [type]: value }
    case ValType.f64:
      return { [type]: value }
  }
}

const compileFunction = (ast: ASTFunction): WASMCode[] => {
  const prologue: WASMCode[] = flatten(
    // initialize local values
    ast.locals.map((l, i) => [
      {
        opType: `${l.type}.const`,
        parameters: [numberValue(l.type, "0")]
      },
      { opType: "set_local", parameters: [i + ast.parameters.length] }
    ])
  )

  const body = flatten(ast.body.map(i => compileInstruction(i)))

  return [...prologue, ...body]
}

// Compiles AST generated by wat-parser.ts into machine code for wasm-vm.ts.
export const compile = (ast: ASTModule): WASMModule => {
  ast = replaceIdentifiers(ast)

  // TODO: functions 以外を実装

  const functions = ast.functions.map(fn => ({
    export: fn.export,
    results: fn.results,
    identifier: fn.identifier,
    locals: fn.locals.map(l => l.type),
    parameters: fn.parameters.map(p => p.type),
    code: compileFunction(fn)
  }))

  const table: { [key: number]: number } = {}
  ast.elems.forEach(e => {
    const offset = Int32.obj(e.offset).toNumber()
    e.funcIds.forEach((id, i) => {
      table[offset + i] = id as number
    })
  })

  return {
    functions,
    table
  }
}
